name: jokes_app
description: Jokes App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  dio: ^4.0.6
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  freezed_annotation: ^2.2.0
  collection: ^1.16.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  hive_generator: ^1.1.3
  json_serializable: ^6.3.1
  mockito: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
